# <center> Text Generation - Next Word Prediction

## 1. Functions for Processing Text

### a. Reading in files as a string text

In [1]:
def read_file(filepath):

    with open(filepath) as f:
        str_text = f.read()

    return str_text

In [2]:
len("rahul")

5

In [3]:
len(read_file('/content/Novel - Moby-Dick By Herman Melville.txt'))

1198622

In [4]:
print(read_file('/content/Novel - Moby-Dick By Herman Melville.txt')[:5000])

CHAPTER 1

Loomings.


Call me Ishmael.  Some years ago--never mind how long
precisely--having little or no money in my purse, and nothing
particular to interest me on shore, I thought I would sail about a
little and see the watery part of the world.  It is a way I have of
driving off the spleen and regulating the circulation.  Whenever I
find myself growing grim about the mouth; whenever it is a damp,
drizzly November in my soul; whenever I find myself involuntarily
pausing before coffin warehouses, and bringing up the rear of every
funeral I meet; and especially whenever my hypos get such an upper
hand of me, that it requires a strong moral principle to prevent me
from deliberately stepping into the street, and methodically knocking
people's hats off--then, I account it high time to get to sea as soon
as I can.  This is my substitute for pistol and ball.  With a
philosophical flourish Cato throws himself upon his sword; I quietly
take to the ship.  There is nothing surprising in this

### b. Tokenize and Clean Text

In [5]:
import spacy
import en_core_web_sm

nlp = en_core_web_sm.load()
nlp.max_length = 1198623

In [6]:
def read_file(filepath):

    with open(filepath) as f:
        str_text = f.read()

    return str_text[:250000]

In [7]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [8]:
d = read_file('/content/Novel - Moby-Dick By Herman Melville.txt')
tokens = separate_punc(d)

In [9]:
type(tokens)

list

In [10]:
len(tokens)

45279

In [11]:
tokens[:10]

['chapter',
 '1',
 'loomings',
 'call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never']

### c. Create Sequences of Tokens

In [12]:
# organize into sequences of tokens
train_len = 25+1 # 25 training words , then one target word

# Empty list of sequences
text_sequences = []

for i in range(train_len, len(tokens)):

    # Grab train_len# amount of characters
    seq = tokens[i-train_len:i]

    # Add to list of sequences
    text_sequences.append(seq)

In [13]:
print(read_file('/content/Novel - Moby-Dick By Herman Melville.txt')[:1000])

CHAPTER 1

Loomings.


Call me Ishmael.  Some years ago--never mind how long
precisely--having little or no money in my purse, and nothing
particular to interest me on shore, I thought I would sail about a
little and see the watery part of the world.  It is a way I have of
driving off the spleen and regulating the circulation.  Whenever I
find myself growing grim about the mouth; whenever it is a damp,
drizzly November in my soul; whenever I find myself involuntarily
pausing before coffin warehouses, and bringing up the rear of every
funeral I meet; and especially whenever my hypos get such an upper
hand of me, that it requires a strong moral principle to prevent me
from deliberately stepping into the street, and methodically knocking
people's hats off--then, I account it high time to get to sea as soon
as I can.  This is my substitute for pistol and ball.  With a
philosophical flourish Cato throws himself upon his sword; I quietly
take to the ship.  There is nothing surprising in this

In [14]:
' '.join(text_sequences[0])

'chapter 1 loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to'

In [15]:
' '.join(text_sequences[1])

'1 loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest'

In [16]:
' '.join(text_sequences[2])

'loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me'

In [17]:
len(text_sequences) #Every sentence is containing 26 words

45253

In [18]:
len(tokens) # These are total number of words in the whole novel

45279

In [19]:
print(len(text_sequences[0]))
print(text_sequences[0])

26
['chapter', '1', 'loomings', 'call', 'me', 'ishmael', 'some', 'years', 'ago', 'never', 'mind', 'how', 'long', 'precisely', 'having', 'little', 'or', 'no', 'money', 'in', 'my', 'purse', 'and', 'nothing', 'particular', 'to']


### d. Keras Tokenization

In [20]:
from keras.preprocessing.text import Tokenizer

In [21]:
# integer encode sequences of words
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)

In [22]:
print(len(sequences[0]))
print(sequences[0])

26
[187, 7000, 6999, 516, 24, 432, 65, 232, 640, 100, 223, 99, 93, 1331, 277, 68, 48, 36, 639, 6, 31, 1028, 2, 150, 431, 5]


In [23]:
type(tokenizer.index_word)

dict

In [24]:
' '.join(text_sequences[0])

'chapter 1 loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to'

In [25]:
i=0
for a in tokenizer.index_word:
    print(a,"--->",tokenizer.index_word[a])
    i+=1
    if i==20 : break

1 ---> the
2 ---> and
3 ---> of
4 ---> a
5 ---> to
6 ---> in
7 ---> i
8 ---> that
9 ---> his
10 ---> he
11 ---> it
12 ---> was
13 ---> but
14 ---> with
15 ---> all
16 ---> for
17 ---> as
18 ---> 's
19 ---> at
20 ---> is


In [26]:
for i in sequences[0]:
    print(f'{i} : {tokenizer.index_word[i]}')

187 : chapter
7000 : 1
6999 : loomings
516 : call
24 : me
432 : ishmael
65 : some
232 : years
640 : ago
100 : never
223 : mind
99 : how
93 : long
1331 : precisely
277 : having
68 : little
48 : or
36 : no
639 : money
6 : in
31 : my
1028 : purse
2 : and
150 : nothing
431 : particular
5 : to


In [27]:
i=0
for a in tokenizer.word_counts:
    print((a,tokenizer.word_counts[a]))
    i+=1
    if i==10 : break

('chapter', 807)
('1', 2)
('loomings', 3)
('call', 238)
('me', 6214)
('ishmael', 292)
('some', 2451)
('years', 606)
('ago', 191)
('never', 1700)


In [28]:
vocabulary_size = len(tokenizer.word_counts)
vocabulary_size

7000

In [29]:
i=6990
for a in range(i,7000):
    print(a,"--->",tokenizer.index_word[a])
    #i+=1
    #if i==6999 : break

6990 ---> subtle
6991 ---> conceived
6992 ---> poorly
6993 ---> moods
6994 ---> whimsicalities
6995 ---> apprehensiveness
6996 ---> uneasiness
6997 ---> warrantry
6998 ---> emotions
6999 ---> loomings


In [30]:
# tokenizer.index_word

### e. Convert to Numpy Matrix

In [31]:
import numpy as np

In [32]:
len(sequences)

45253

In [33]:
len(sequences[0])

26

In [34]:
sequences = np.array(sequences)

In [35]:
sequences.shape

(45253, 26)

In [36]:
sequences

array([[ 187, 7000, 6999, ...,  150,  431,    5],
       [7000, 6999,  516, ...,  431,    5,  734],
       [6999,  516,   24, ...,    5,  734,   24],
       ...,
       [  86,  578,    7, ...,  472,   14,    1],
       [ 578,    7,  171, ...,   14,    1,  111],
       [   7,  171,    5, ...,    1,  111,  577]])

## 2. Creating an LSTM based model

In [37]:
import keras
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [38]:
def create_model(vocabulary_size, seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size, 25, input_length=seq_len))
    model.add(LSTM(150, return_sequences=True))
    model.add(LSTM(150))
    model.add(Dense(150, activation='relu'))

    model.add(Dense(vocabulary_size, activation='softmax'))

    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    model.summary()

    return model

## 3. Train / Test Split

In [39]:
from tensorflow.keras.utils import to_categorical

In [40]:
print(sequences.shape)
sequences

(45253, 26)


array([[ 187, 7000, 6999, ...,  150,  431,    5],
       [7000, 6999,  516, ...,  431,    5,  734],
       [6999,  516,   24, ...,    5,  734,   24],
       ...,
       [  86,  578,    7, ...,  472,   14,    1],
       [ 578,    7,  171, ...,   14,    1,  111],
       [   7,  171,    5, ...,    1,  111,  577]])

In [41]:
# First 25 words
print(sequences[:,:-1].shape)
sequences[:,:-1]

(45253, 25)


array([[ 187, 7000, 6999, ...,    2,  150,  431],
       [7000, 6999,  516, ...,  150,  431,    5],
       [6999,  516,   24, ...,  431,    5,  734],
       ...,
       [  86,  578,    7, ...,    1,  472,   14],
       [ 578,    7,  171, ...,  472,   14,    1],
       [   7,  171,    5, ...,   14,    1,  111]])

In [42]:
# last Word
print(sequences[:,-1].shape)
sequences[:,-1]

(45253,)


array([  5, 734,  24, ...,   1, 111, 577])

In [43]:
X = sequences[:,:-1]

In [44]:
X.shape

(45253, 25)

In [45]:
y = sequences[:,-1]

In [46]:
y.shape

(45253,)

In [47]:
y = to_categorical(y, num_classes=vocabulary_size)

In [48]:
y.shape

(45253, 7000)

In [49]:
seq_len = X.shape[1]

In [50]:
seq_len

25

## 4. Training the Model

In [51]:
# define model
model = create_model(vocabulary_size, seq_len)
#model = create_model(vocabulary_size, seq_len)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 25, 25)            175000    
                                                                 
 lstm (LSTM)                 (None, 25, 150)           105600    
                                                                 
 lstm_1 (LSTM)               (None, 150)               180600    
                                                                 
 dense (Dense)               (None, 150)               22650     
                                                                 
 dense_1 (Dense)             (None, 7000)              1057000   
                                                                 
Total params: 1540850 (5.88 MB)
Trainable params: 1540850 (5.88 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


---

----

## 5. Fit model

In [ ]:
model.fit(X, y, batch_size=512, epochs=250,verbose=1,validation_batch_size=.20)

Epoch 1/250
89/89 [==============================] - 16s 127ms/step - loss: 1.8545 - accuracy: 0.5578
Epoch 2/250
89/89 [==============================] - 6s 71ms/step - loss: 1.8498 - accuracy: 0.5572
Epoch 3/250
89/89 [==============================] - 5s 57ms/step - loss: 1.8361 - accuracy: 0.5612
Epoch 4/250
89/89 [==============================] - 3s 37ms/step - loss: 1.8301 - accuracy: 0.5628
Epoch 5/250
89/89 [==============================] - 4s 47ms/step - loss: 1.8264 - accuracy: 0.5625
Epoch 6/250
89/89 [==============================] - 3s 33ms/step - loss: 1.8143 - accuracy: 0.5644
Epoch 7/250
89/89 [==============================] - 3s 37ms/step - loss: 1.8011 - accuracy: 0.5668
Epoch 8/250
89/89 [==============================] - 3s 38ms/step - loss: 1.7921 - accuracy: 0.5701
Epoch 9/250
89/89 [==============================] - 3s 31ms/step - loss: 1.7885 - accuracy: 0.5703
Epoch 10/250
89/89 [==============================] - 3s 33ms/step - loss: 1.7770 - accuracy: 0.57

### Download Model Object

In [73]:
from pickle import dump,load

In [74]:
# save the model to file
model.save('epochBIG.h5')
# save the tokenizer
dump(tokenizer, open('epochBIG', 'wb'))

## 6. Generating New Text

In [ ]:
from random import randint
from pickle import load
from keras.models import load_model
from keras.preprocessing.sequence import pad_sequences

In [75]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    '''
    INPUTS:
    model : model that was trained on text data
    tokenizer : tokenizer that was fit on text data
    seq_len : length of training sequence
    seed_text : raw string text to serve as the seed
    num_gen_words : number of words to be generated by model
    '''

    # Final Output
    output_text = []

    # Intial Seed Sequence
    input_text = seed_text

    # Create num_gen_words
    for i in range(num_gen_words):

        # Take the input text string and encode it to a sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]

        # Pad sequences to our trained rate (25 words in the video)
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')

        # Predict Class Probabilities for each word
        #pred_word_ind = model.predict_classes(pad_encoded, verbose=0)[0]
        predict_x=model.predict(pad_encoded)
        pred_word_ind=np.argmax(predict_x,axis=1)[0]
        #print(pred_word_ind)
        # Grab word
        pred_word = tokenizer.index_word[pred_word_ind]

        # Update the sequence of input text (shifting one over with the new word)
        input_text += ' ' + pred_word

        output_text.append(pred_word)

    # Make it look like a sentence.
    return ' '.join(output_text)

## 7. Grab a random Text Sequence

In [76]:
print(text_sequences[0])

['chapter', '1', 'loomings', 'call', 'me', 'ishmael', 'some', 'years', 'ago', 'never', 'mind', 'how', 'long', 'precisely', 'having', 'little', 'or', 'no', 'money', 'in', 'my', 'purse', 'and', 'nothing', 'particular', 'to']


In [77]:
import random
random_pick = random.randint(0,len(text_sequences))

In [78]:
random_seed_text = text_sequences[random_pick]

In [79]:
print(random_seed_text)

['take', 'my', 'word', 'for', 'it', 'you', 'never', 'saw', 'such', 'a', 'rare', 'old', 'craft', 'as', 'this', 'same', 'rare', 'old', 'pequod', 'she', 'was', 'a', 'ship', 'of', 'the', 'old']


In [80]:
seed_text = ' '.join(random_seed_text)
seed_text

'take my word for it you never saw such a rare old craft as this same rare old pequod she was a ship of the old'

In [81]:
model = load_model('epochBIG.h5')

In [82]:
tokenizer = load(open('epochBIG', 'rb'))

In [83]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=3)

1/1 [==============================] - 0s 17ms/step


'school rather small'

In [84]:
text=' It is a way I have of driving off the spleen and regulating the circulation.  Whenever I find'
print(text)

 It is a way I have of driving off the spleen and regulating the circulation.  Whenever I find


In [85]:
generate_text(model,tokenizer,seq_len,seed_text=text,num_gen_words=3)

1/1 [==============================] - 0s 18ms/step


'it tell queequeg'

In [86]:
print(read_file('/content/Novel - Moby-Dick By Herman Melville.txt')[250000:251000])

In [87]:
test_text='Three better,more likely sea-officers and men, each in his own different way,could not readily be found, and they were every'
print(test_text)

Three better,more likely sea-officers and men, each in his own different way,could not readily be found, and they were every


In [88]:
generate_text(model,tokenizer,seq_len,seed_text=test_text,num_gen_words=1)

1/1 [==============================] - 0s 19ms/step


'day'

In [89]:
seed_text = "landsman has had fresh fruit to his daily hand and broken the world 's fresh bread to my mouldy crusts away whole oceans away from that"

In [93]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=300)

1/1 [==============================] - 0s 25ms/step


'important subject or more like a man comfortably in that respect you had only at last rising in some other at first watery word if for shall they have been carted to make to pour shipmates therein i are all over the half behind must have told him in some time to settle a shirt or deacon deuteronomy than him which joy the man casts me that continuous eyes or after the pilot of a man was sweet knocking this confidence with a may got but all the fact of the fishery in the ships yet flingers of me and to spring bildad did this biscuit and worthy that with a regular chief in by polished agony do that growl twos and wail in hand and judges delight,--top than poor that dumplings ye will have a little damaged so harpooneer you stand a long breath that cried that because more lay my friends was sin stubb come visit the whole to find of him though terrors of it doubtless yourself centre upon lath and plaster tied to engage for woe of the room the architect stood the other employed of sun said t